
modLoader="javafml"
loaderVersion="[39,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
	modId="hotchocolate"
	version="1.0"
	displayName="Hot Chocolate"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
	logoFile="hotchocolate.png"
	credits="HexagonNico"
	authors="HexagonNico"
	description="This mod adds hot chocolate because why not"

[[dependencies.hotchocolate]]
	modId="forge"
	mandatory=true
	versionRange="[39,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.hotchocolate]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.1,1.19)"
	ordering="NONE"
	side="BOTH"
